### ISSUE TITLE
UI Design looks quite ugly and app is not fully functional

### ISSUE THREAD

**Issue by merkel1860** [RebecaCazeau/Homework_swing#1]
Hi,
Je reviens des deux propositions, j'avoue que c'est bien le travail, mais c'est en plus laid de ce que je me rappelle, sinon, les fonctionnalités ne sont pas opérationnelles.

Cordialement

**Comment by RebecaCazeau** [comment]
Vous nous avez demandé de nous appuyer sur le modèle de notre téléphone,
c'est ce que j"ai fait, et en plus c'est pas fonctionnel parce que vous
nous avez dit  de faire l'interface uniquement pour le moment
Cordialement,
